name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    name: Build Vue.js site and deploy to Cloudflare Workers
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@master

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: Build Vue.js website
        run: yarn run build

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
